// examples/react/src/ChangeLanguage/index.tsx
import { type ChangeEvent, useCallback } from 'react'
import {
  type AvailableLanguages,
  languages,
  useLanguage,
  useTranslate,
} from '../config'
import i18n from './i18n.json'

export function ChangeLanguage() {
  const [language, changeLanguage] = useLanguage()

  const t = useTranslate(i18n)

  const handleChange = useCallback(
    (e: ChangeEvent<HTMLSelectElement>) => {
      changeLanguage(e.target.value as AvailableLanguages)
    },
    [changeLanguage],
  )

  return (
    <select value={language} onChange={handleChange}>
      {languages.map((lang) => (
        <option key={lang} value={lang}>
          {t(lang)}
        </option>
      ))}
    </select>
  )
}

// example/svelte/src/ChangeLanguage.svelte
<script lang="ts">
  import literals from './ChangeLanguage.i18n.json'
  import {
    AvailableLanguages,
    languages,
    useLanguage,
    useTranslate,
  } from './config'

  const t = useTranslate(literals)
  const [lang, changeLanguage] = useLanguage()

  function handleSelect(e: Event) {
    const target = e.target as HTMLSelectElement
    console.log('handleSelect', target.value)
    changeLanguage(target.value as AvailableLanguages)
  }
</script>

<select value={$lang} on:input={handleSelect}>
  {#each languages as lang (lang)}
    <option value={lang}>
      {$t(lang)}
    </option>
  {/each}
</select>
